project:
  type: website
  output-dir: docs

website:
  title: "Espi Web"
  favicon: images/logo.png
  site-url: https://isaiahespi.github.io/espi-web/
  repo-url: https://github.com/isaiahespi/espi-web
  search:
    location: navbar
    type: overlay
  back-to-top-navigation: true
  page-footer:
    left: "Copyright 2023, Isaiah Espinoza"
    right:
      - icon: github
        href: https://github.com/isaiahespi
        aria-label: GitHub
  comments: 
    hypothesis:
      theme: clean
      openSidebar: false
  navbar: 
    title: false
    logo: images/logo2.png
    logo-alt: "Korean name seal"
    tools:
      - icon: github
        menu:
          - text: Source Code
            url: https://github.com/isaiahespi/espi-web
          - text: Github Profile
            url: https://github.com/isaiahespi
    left:
      - file: index.qmd
        text: Home
      - about.qmd
      - tutorials.qmd
      - file: resources.qmd
        text: Resources
  

format:
  html:
    theme: 
      dark: [solar, dark-custom.scss]
      light: [solar, light-custom.scss]
    toc: true

