project:
  type: website
  output-dir: docs

website:
  title: "Isaiah Espinoza"
  favicon: images/logo.png
  site-url: https://isaiahespi.github.io/espi-web/
  repo-url: https://github.com/isaiahespi/espi-web
  search:
    location: navbar
    type: overlay
  back-to-top-navigation: true
  page-footer:
    left: "Copyright 2023, Isaiah Espinoza"
    right:
      - icon: github
        href: https://github.com/isaiahespi
        aria-label: GitHub
  navbar: 
    title: false
    logo: images/logo2.png
    logo-alt: "Korean name seal"
    tools:
      - icon: github
        menu:
          - text: Source Code
            url: https://github.com/isaiahespi/espi-web
          - text: Github Profile
            url: https://github.com/isaiahespi
    left:
      - file: index.qmd
        text: Home
      - sidebar:tutorials
      - sidebar:resources
      - text: C.V.
        file: cv.qmd
  sidebar:
    - id: tutorials
      title: "Tutorials"
      style: "docked"
      background: dark
      collapse-level: 2
      contents:
        - tutorials.qmd
        
    - id: resources
      title: "Resources"
      contents:
        - resources.qmd
        - books.qmd
        - methods.qmd

        
        
format:
  html:
    theme: 
      dark: [solar, dark-custom.scss]
      light: [solar, light-custom.scss]
    toc: true

