project:
  type: website
  output-dir: docs

website:
  title: "Espi Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: solar
    mainfont: Palatino Linotype
      dark: [solar, dark-custom.scss]
      light: [solar, light-custom.scss]
    css: styles.css
    toc: true

