project:
  type: website
  output-dir: docs

website:
  title: "Espi Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      dark: [cosmo, dark-custom.scss]
      light: [cosmo, light-custom.scss]
    css: styles.css
    toc: true

