project:
  type: website
  output-dir: docs

website:
  title: "Espi Web"
  favicon: images/logo.png
  site-url: https://isaiahespi.github.io/espi-web/
  repo-url: https://github.com/isaiahespi/espi-web
  reader-mode: true
  search:
    location: navbar
    type: overlay
  page-footer:
    left: "Copyright 2023, Isaiah Espinoza"
    right:
      - icon: github
        href: https://github.com/isaiahespi
        aria-label: GitHub
  navbar: 
    title: false
    logo: images/logo2.png
    logo-alt: "Korean name seal"
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - hypothesis.qmd
  comments: 
    hypothesis:
      theme: clean
      openSidebar: false
  sidebar: 
    style: docked
    contents: auto

format:
  html:
    theme: 
      dark: [solar, dark-custom.scss]
      light: [solar, light-custom.scss]
    toc: true

